In [2]:
import numpy as np
import tensorflow as tf
%matplotlib inline
import matplotlib.pyplot as plt

In [114]:
wave_num=4
sz=64
def createGraph():
    rnd_f=0.04+0.16*tf.random_uniform([wave_num,1])
    rnd_p=np.pi*tf.random_uniform([wave_num,1])

    idx = tf.reshape(tf.constant(np.arange(sz,dtype=np.float32)),[1,sz])
    y=idx*rnd_f*np.pi+rnd_p
    return tf.sin(y)

with tf.Session() as sess:
    g=createGraph()
    waves=sess.run(g)

[[ 0.16449608  0.63394958  0.93492657]
 [ 0.07989933  0.32995811  0.55846471]
 [ 0.82875931  0.99877089  0.88009304]
 [ 0.07968804  0.63745064  0.96424973]]


In [109]:
for i in range(len(waves)):
    np.save("{0:0>8}".format(i) + ".npy", waves[i])

In [3]:
import glob
filepaths = glob.glob("../data/input/training/*.npy")
waves = []
for path in filepaths:
    w = np.load(path)
    waves.append(w)